CREATE TABLE IF NOT EXISTS users (
user_id TEXT NOT NULL PRIMARY KEY,
tokens INT DEFAULT 0 NOT NULL,
blocked BOOLEAN NOT NULL DEFAULT false,
last_played TIMESTAMP DEFAULT NOW(),
money_spent INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
message_id SERIAL PRIMARY KEY,
user_id TEXT NOT NULL,
text TEXT DEFAULT NULL,
sent BOOLEAN NOT NULL DEFAULT false,
taken_by TEXT NULL,
time TIMESTAMP NOT NULL DEFAULT NOW(),
FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS session (
user_id TEXT NOT NULL,
session_id SERIAL PRIMARY KEY,
start TIMESTAMP,
stop TIMESTAMP,
power INT NOT NULL DEFAULT 1,
game TEXT NOT NULL DEFAULT 'mc',
FOREIGN KEY (user_id) REFERENCES users(user_id)
);
