FROM python:bullseye

# copy requirements file from host to container
COPY requirements.txt .

# install requirements
RUN apt-get update \
    && apt-get upgrade -y \
    && pip install -U pip \
    && pip install -r requirements.txt
